global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "services"
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:8001
          - catalog-service:8002
          - search-service:8003
          - cart-service:8004
          - order-service:8005
        labels:
          group: app

  - job_name: "tempo"
    metrics_path: /metrics
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]

remote_write:
  - url: http://mimir:9009/api/v1/push
    headers:
      X-Scope-OrgID: anonymous
